#!/bin/bash

set -e

repo=$(dirname "${BASH_SOURCE[0]}")
repo=$(realpath $repo/..)

TARGETARCH="${TARGETARCH:-amd64}"

rust_version=$(grep channel $repo/rust-toolchain.toml | cut -d '"' -f 2)
image=rust:$rust_version-bookworm

user_cargo_home=$CARGO_HOME
[[ -z $user_cargo_home ]] && [[ -d "$HOME/.cargo" ]] && user_cargo_home="$HOME/.cargo"

docker_cargo_home=$(docker run --rm $image sh -c 'echo $CARGO_HOME')

[[ -n $user_cargo_home ]] && mount_cargo="-v $user_cargo_home/git:$docker_cargo_home/git -v $user_cargo_home/registry:$docker_cargo_home/registry "

version=$(git describe --dirty) || { echo "error: no annotated tag found"; exit 1; }
tmp_cargo=$(mktemp /tmp/Cargo.XXXXXX)
cat $repo/Cargo.toml | sed -e "s/version = \"0.0.0-dev\"/version = \"$version\"/" > $tmp_cargo

tmp_rust_toolchain=$(mktemp /tmp/rust-toolchain.XXXXXX)
grep -v components $repo/rust-toolchain.toml > $tmp_rust_toolchain

docker_tty=""
[[ -t 1 ]] && docker_tty="-t"

docker run --rm \
    $docker_tty \
    --platform linux/$TARGETARCH \
    --user "$(id -u)":"$(id -g)" \
    -e CARGO_TARGET_DIR="./target/$TARGETARCH" \
    -v "$repo":"$repo" \
    -v $tmp_cargo:"$repo/Cargo.toml" \
    -v $tmp_rust_toolchain:"$repo/rust-toolchain.toml" \
    $mount_cargo \
    -w "$repo" \
    $image \
    "$@"

rm $tmp_cargo
rm $tmp_rust_toolchain
