#!/bin/bash

set -e

repo=$(dirname "${BASH_SOURCE[0]}")
repo=$(realpath $repo/..)

TARGETARCH="${TARGETARCH:-amd64}"

# Set architecture-specific C/C++ optimization flags for native deps (USearch/SimSIMD)
case "$TARGETARCH" in
    arm64)
        export CXXFLAGS="${CXXFLAGS:--march=armv8.4-a+sve}"
        export CFLAGS="${CFLAGS:--march=armv8.4-a+sve}"
        ;;
esac

rust_version=$(grep channel $repo/rust-toolchain.toml | cut -d '"' -f 2)
image=rust:$rust_version-bookworm

user_cargo_home=$CARGO_HOME
[[ -z $user_cargo_home ]] && [[ -d "$HOME/.cargo" ]] && user_cargo_home="$HOME/.cargo"

docker_cargo_home=$(docker run --rm $image sh -c 'echo $CARGO_HOME')

tmp_rust_toolchain=$(mktemp /tmp/rust-toolchain.XXXXXX)
grep -v components $repo/rust-toolchain.toml > $tmp_rust_toolchain

docker run --rm \
    --platform linux/$TARGETARCH \
    --user "$(id -u)":"$(id -g)" \
    -e CARGO_TARGET_DIR="./target/$TARGETARCH" \
    ${CXXFLAGS:+-e CXXFLAGS="$CXXFLAGS"} \
    ${CFLAGS:+-e CFLAGS="$CFLAGS"} \
    -v "$repo":"$repo" \
    -v "$user_cargo_home/git":"$docker_cargo_home/git" \
    -v "$user_cargo_home/registry":"$docker_cargo_home/registry" \
    -v $tmp_rust_toolchain:"$repo/rust-toolchain.toml" \
    -w "$repo" \
    $image \
    "$@"

rm $tmp_rust_toolchain
